### ISSUE TITLE
Reduce Technical Debt and Optimize Code in SafeShop

### ISSUE THREAD

**Issue by empea-careercriminal** [empea-careercriminal/safe_dummy#10]
**Issue Description:*
Address technical debt in SafeShop and optimize the code for better performance, especially for integration with Safe{Core} components.

**Triage Notes**
Important for long-term project sustainability, post-primary integrations.

**Tasks**
- [ ] Identify areas of technical debt.
- [ ] Refactor and optimize existing code.
- [ ] Test for improved performance and stability.
